# Generated by Django 2.0 on 2018-01-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180113_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_key_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
